controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
    # config/routes.yaml
home:
    path: home
    controller: App\Controller\HomeController::index
login:
    path: login
    controller: App\controller\SecurityController::login
register:
    path: register
    controller: App\controller\RegistrationController::register
